### ISSUE TITLE
May i ask how do you actually parse the data? I meant where did you get it from?

### ISSUE THREAD

**Issue by dentalmisorder** [Dimbreath/StarRailData#2]
If you dont mind me asking, how do you know what to parse and where to knock (if thats a http request like webstatic0.mihoyo or smth) for getting those infos? Or you getting it from pc files, could you give a hint where to look?

Any feedback would been helpful, thanks

**Comment by Eleiyas** [comment]
It's Dimbreath's secret sauce

**Comment by davispuh** [comment]
Stupid, I'm also looking for this. My guess is they probably run game and load their DLL that invoke's games functions to extract data that way.

**Comment by dentalmisorder** [comment]
nvm, i did it

**Comment by Vocaloid2048** [comment]
> nvm, i did it

Sorry for disturbing u, may I ask how did u achieve it? Thx if possible!
