### ISSUE TITLE
some fields missing TextMap Hash

### ISSUE THREAD

**Issue by yueecui** [Dimbreath/StarRailData#4]
Hello,

I would like to create a website using your data. While inspecting the data, I noticed that the following fields are missing TextMap Hash data:

- AvatarSkillTree
  - PointName
  - PointDesc
- MissionChapterConfig
  - ChapterName
  - ChapterDesc
- RelicDataInfo
  - RelicName
  - ItemBGDesc
  - BGStoryTitle
  - BGStoryContent
- RelicSetSkillConfig
  - SkillDesc

If possible, could you please help me add the missing data? Thank you very much!

**Comment by yueecui** [comment]
got it! thanks!

**Comment by Zyr0nX** [comment]
How did you find the missing hash?

**Comment by Zyr0nX** [comment]
What is the str parameter?

**Comment by yueecui** [comment]
> What is the str parameter?

like AvatarSkillTree PointName value
example: SkillPointName_1001101
result: 2078331665

**Comment by Zyr0nX** [comment]
Thank you
