### ISSUE TITLE
What is the Hash Number 371857150?

### ISSUE THREAD

**Issue by moon5ckq** [Dimbreath/StarRailData#6]
A number of Hash values of 371857150 have been found in the data, but this hash value is not present in the TextMap. 
What does this hash value correspond to? Can it be understood as an empty value?

**Comment by Eleiyas** [comment]
> A number of Hash values of 371857150 have been found in the data, but this hash value is not present in the TextMap. What does this hash value correspond to? Can it be understood as an empty value?

if it doesn't exist, then yeah, might as well just consider it an empty value

**Comment by kwwxis** [comment]
`371857150` in particular corresponds to an empty string, but you can just think of it as `null`

![image](https://github.com/Dimbreath/StarRailData/assets/118708201/7e98b320-6985-4254-b25f-2c227b3749d6)
